/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CriteriaGroupCreateNestedManyWithoutRubricsInput } from "./CriteriaGroupCreateNestedManyWithoutRubricsInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { MarksBandCreateNestedManyWithoutRubricsInput } from "./MarksBandCreateNestedManyWithoutRubricsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { SectionCreateNestedManyWithoutRubricsInput } from "./SectionCreateNestedManyWithoutRubricsInput";
@InputType()
class RubricCreateInput {
  @ApiProperty({
    required: false,
    type: () => CriteriaGroupCreateNestedManyWithoutRubricsInput,
  })
  @ValidateNested()
  @Type(() => CriteriaGroupCreateNestedManyWithoutRubricsInput)
  @IsOptional()
  @Field(() => CriteriaGroupCreateNestedManyWithoutRubricsInput, {
    nullable: true,
  })
  criteriaGroups?: CriteriaGroupCreateNestedManyWithoutRubricsInput;

  @ApiProperty({
    required: false,
    type: () => MarksBandCreateNestedManyWithoutRubricsInput,
  })
  @ValidateNested()
  @Type(() => MarksBandCreateNestedManyWithoutRubricsInput)
  @IsOptional()
  @Field(() => MarksBandCreateNestedManyWithoutRubricsInput, {
    nullable: true,
  })
  marksBands?: MarksBandCreateNestedManyWithoutRubricsInput;

  @ApiProperty({
    required: true,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @Field(() => UserWhereUniqueInput)
  owner!: UserWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => SectionCreateNestedManyWithoutRubricsInput,
  })
  @ValidateNested()
  @Type(() => SectionCreateNestedManyWithoutRubricsInput)
  @IsOptional()
  @Field(() => SectionCreateNestedManyWithoutRubricsInput, {
    nullable: true,
  })
  sections?: SectionCreateNestedManyWithoutRubricsInput;
}
export { RubricCreateInput };
