/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { RubricService } from "../rubric.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RubricCreateInput } from "./RubricCreateInput";
import { RubricWhereInput } from "./RubricWhereInput";
import { RubricWhereUniqueInput } from "./RubricWhereUniqueInput";
import { RubricFindManyArgs } from "./RubricFindManyArgs";
import { RubricUpdateInput } from "./RubricUpdateInput";
import { Rubric } from "./Rubric";
import { CriteriaGroupFindManyArgs } from "../../criteriaGroup/base/CriteriaGroupFindManyArgs";
import { CriteriaGroup } from "../../criteriaGroup/base/CriteriaGroup";
import { CriteriaGroupWhereUniqueInput } from "../../criteriaGroup/base/CriteriaGroupWhereUniqueInput";
import { MarksBandFindManyArgs } from "../../marksBand/base/MarksBandFindManyArgs";
import { MarksBand } from "../../marksBand/base/MarksBand";
import { MarksBandWhereUniqueInput } from "../../marksBand/base/MarksBandWhereUniqueInput";
import { SectionFindManyArgs } from "../../section/base/SectionFindManyArgs";
import { Section } from "../../section/base/Section";
import { SectionWhereUniqueInput } from "../../section/base/SectionWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class RubricControllerBase {
  constructor(
    protected readonly service: RubricService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Rubric",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Rubric })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: RubricCreateInput): Promise<Rubric> {
    return await this.service.create({
      data: {
        ...data,

        owner: {
          connect: data.owner,
        },
      },
      select: {
        createdAt: true,
        id: true,

        owner: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Rubric",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Rubric] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(RubricFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Rubric[]> {
    const args = plainToClass(RubricFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,

        owner: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Rubric",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Rubric })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: RubricWhereUniqueInput
  ): Promise<Rubric | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,

        owner: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Rubric",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Rubric })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: RubricWhereUniqueInput,
    @common.Body() data: RubricUpdateInput
  ): Promise<Rubric | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          owner: {
            connect: data.owner,
          },
        },
        select: {
          createdAt: true,
          id: true,

          owner: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Rubric",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Rubric })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: RubricWhereUniqueInput
  ): Promise<Rubric | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,

          owner: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "CriteriaGroup",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/criteriaGroups")
  @ApiNestedQuery(CriteriaGroupFindManyArgs)
  async findManyCriteriaGroups(
    @common.Req() request: Request,
    @common.Param() params: RubricWhereUniqueInput
  ): Promise<CriteriaGroup[]> {
    const query = plainToClass(CriteriaGroupFindManyArgs, request.query);
    const results = await this.service.findCriteriaGroups(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        name: true,

        rubric: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Rubric",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/criteriaGroups")
  async connectCriteriaGroups(
    @common.Param() params: RubricWhereUniqueInput,
    @common.Body() body: CriteriaGroupWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      criteriaGroups: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Rubric",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/criteriaGroups")
  async updateCriteriaGroups(
    @common.Param() params: RubricWhereUniqueInput,
    @common.Body() body: CriteriaGroupWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      criteriaGroups: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Rubric",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/criteriaGroups")
  async disconnectCriteriaGroups(
    @common.Param() params: RubricWhereUniqueInput,
    @common.Body() body: CriteriaGroupWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      criteriaGroups: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "MarksBand",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/marksBands")
  @ApiNestedQuery(MarksBandFindManyArgs)
  async findManyMarksBands(
    @common.Req() request: Request,
    @common.Param() params: RubricWhereUniqueInput
  ): Promise<MarksBand[]> {
    const query = plainToClass(MarksBandFindManyArgs, request.query);
    const results = await this.service.findMarksBands(params.id, {
      ...query,
      select: {
        bottom: true,
        createdAt: true,

        criteriaGroup: {
          select: {
            id: true,
          },
        },

        id: true,
        name: true,

        rubric: {
          select: {
            id: true,
          },
        },

        top: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Rubric",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/marksBands")
  async connectMarksBands(
    @common.Param() params: RubricWhereUniqueInput,
    @common.Body() body: MarksBandWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      marksBands: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Rubric",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/marksBands")
  async updateMarksBands(
    @common.Param() params: RubricWhereUniqueInput,
    @common.Body() body: MarksBandWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      marksBands: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Rubric",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/marksBands")
  async disconnectMarksBands(
    @common.Param() params: RubricWhereUniqueInput,
    @common.Body() body: MarksBandWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      marksBands: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Section",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/sections")
  @ApiNestedQuery(SectionFindManyArgs)
  async findManySections(
    @common.Req() request: Request,
    @common.Param() params: RubricWhereUniqueInput
  ): Promise<Section[]> {
    const query = plainToClass(SectionFindManyArgs, request.query);
    const results = await this.service.findSections(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        name: true,

        rubric: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Rubric",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/sections")
  async connectSections(
    @common.Param() params: RubricWhereUniqueInput,
    @common.Body() body: SectionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      sections: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Rubric",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/sections")
  async updateSections(
    @common.Param() params: RubricWhereUniqueInput,
    @common.Body() body: SectionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      sections: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Rubric",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/sections")
  async disconnectSections(
    @common.Param() params: RubricWhereUniqueInput,
    @common.Body() body: SectionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      sections: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
