/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "nestjs-prisma";
import {
  Prisma,
  Rubric,
  CriteriaGroup,
  MarksBand,
  Section,
  User,
} from "@prisma/client";

export class RubricServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.RubricFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.RubricFindManyArgs>
  ): Promise<number> {
    return this.prisma.rubric.count(args);
  }

  async findMany<T extends Prisma.RubricFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.RubricFindManyArgs>
  ): Promise<Rubric[]> {
    return this.prisma.rubric.findMany(args);
  }
  async findOne<T extends Prisma.RubricFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.RubricFindUniqueArgs>
  ): Promise<Rubric | null> {
    return this.prisma.rubric.findUnique(args);
  }
  async create<T extends Prisma.RubricCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.RubricCreateArgs>
  ): Promise<Rubric> {
    return this.prisma.rubric.create<T>(args);
  }
  async update<T extends Prisma.RubricUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.RubricUpdateArgs>
  ): Promise<Rubric> {
    return this.prisma.rubric.update<T>(args);
  }
  async delete<T extends Prisma.RubricDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.RubricDeleteArgs>
  ): Promise<Rubric> {
    return this.prisma.rubric.delete(args);
  }

  async findCriteriaGroups(
    parentId: string,
    args: Prisma.CriteriaGroupFindManyArgs
  ): Promise<CriteriaGroup[]> {
    return this.prisma.rubric
      .findUnique({
        where: { id: parentId },
      })
      .criteriaGroups(args);
  }

  async findMarksBands(
    parentId: string,
    args: Prisma.MarksBandFindManyArgs
  ): Promise<MarksBand[]> {
    return this.prisma.rubric
      .findUnique({
        where: { id: parentId },
      })
      .marksBands(args);
  }

  async findSections(
    parentId: string,
    args: Prisma.SectionFindManyArgs
  ): Promise<Section[]> {
    return this.prisma.rubric
      .findUnique({
        where: { id: parentId },
      })
      .sections(args);
  }

  async getOwner(parentId: string): Promise<User | null> {
    return this.prisma.rubric
      .findUnique({
        where: { id: parentId },
      })
      .owner();
  }
}
