/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "nestjs-prisma";
import {
  Prisma,
  MarksBand,
  Criterion,
  CriteriaGroup,
  Rubric,
} from "@prisma/client";

export class MarksBandServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.MarksBandFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.MarksBandFindManyArgs>
  ): Promise<number> {
    return this.prisma.marksBand.count(args);
  }

  async findMany<T extends Prisma.MarksBandFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.MarksBandFindManyArgs>
  ): Promise<MarksBand[]> {
    return this.prisma.marksBand.findMany(args);
  }
  async findOne<T extends Prisma.MarksBandFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.MarksBandFindUniqueArgs>
  ): Promise<MarksBand | null> {
    return this.prisma.marksBand.findUnique(args);
  }
  async create<T extends Prisma.MarksBandCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.MarksBandCreateArgs>
  ): Promise<MarksBand> {
    return this.prisma.marksBand.create<T>(args);
  }
  async update<T extends Prisma.MarksBandUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.MarksBandUpdateArgs>
  ): Promise<MarksBand> {
    return this.prisma.marksBand.update<T>(args);
  }
  async delete<T extends Prisma.MarksBandDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.MarksBandDeleteArgs>
  ): Promise<MarksBand> {
    return this.prisma.marksBand.delete(args);
  }

  async findCriteria(
    parentId: string,
    args: Prisma.CriterionFindManyArgs
  ): Promise<Criterion[]> {
    return this.prisma.marksBand
      .findUnique({
        where: { id: parentId },
      })
      .criteria(args);
  }

  async getCriteriaGroup(parentId: string): Promise<CriteriaGroup | null> {
    return this.prisma.marksBand
      .findUnique({
        where: { id: parentId },
      })
      .criteriaGroup();
  }

  async getRubric(parentId: string): Promise<Rubric | null> {
    return this.prisma.marksBand
      .findUnique({
        where: { id: parentId },
      })
      .rubric();
  }
}
