/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsNumber,
  IsDate,
  ValidateNested,
  IsOptional,
  IsString,
} from "class-validator";
import { Type } from "class-transformer";
import { Criterion } from "../../criterion/base/Criterion";
import { CriteriaGroup } from "../../criteriaGroup/base/CriteriaGroup";
import { Rubric } from "../../rubric/base/Rubric";
@ObjectType()
class MarksBand {
  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Field(() => Number)
  bottom!: number;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: () => [Criterion],
  })
  @ValidateNested()
  @Type(() => Criterion)
  @IsOptional()
  criteria?: Array<Criterion>;

  @ApiProperty({
    required: true,
    type: () => CriteriaGroup,
  })
  @ValidateNested()
  @Type(() => CriteriaGroup)
  criteriaGroup?: CriteriaGroup;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: true,
    type: () => Rubric,
  })
  @ValidateNested()
  @Type(() => Rubric)
  rubric?: Rubric;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Field(() => Number)
  top!: number;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}
export { MarksBand };
