/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CriteriaGroupService } from "../criteriaGroup.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CriteriaGroupCreateInput } from "./CriteriaGroupCreateInput";
import { CriteriaGroupWhereInput } from "./CriteriaGroupWhereInput";
import { CriteriaGroupWhereUniqueInput } from "./CriteriaGroupWhereUniqueInput";
import { CriteriaGroupFindManyArgs } from "./CriteriaGroupFindManyArgs";
import { CriteriaGroupUpdateInput } from "./CriteriaGroupUpdateInput";
import { CriteriaGroup } from "./CriteriaGroup";
import { MarksBandFindManyArgs } from "../../marksBand/base/MarksBandFindManyArgs";
import { MarksBand } from "../../marksBand/base/MarksBand";
import { MarksBandWhereUniqueInput } from "../../marksBand/base/MarksBandWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CriteriaGroupControllerBase {
  constructor(
    protected readonly service: CriteriaGroupService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "CriteriaGroup",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CriteriaGroup })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: CriteriaGroupCreateInput
  ): Promise<CriteriaGroup> {
    return await this.service.create({
      data: {
        ...data,

        rubric: {
          connect: data.rubric,
        },
      },
      select: {
        createdAt: true,
        id: true,
        name: true,

        rubric: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "CriteriaGroup",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [CriteriaGroup] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(CriteriaGroupFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<CriteriaGroup[]> {
    const args = plainToClass(CriteriaGroupFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,

        rubric: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "CriteriaGroup",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CriteriaGroup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: CriteriaGroupWhereUniqueInput
  ): Promise<CriteriaGroup | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,

        rubric: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "CriteriaGroup",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CriteriaGroup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: CriteriaGroupWhereUniqueInput,
    @common.Body() data: CriteriaGroupUpdateInput
  ): Promise<CriteriaGroup | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          rubric: {
            connect: data.rubric,
          },
        },
        select: {
          createdAt: true,
          id: true,
          name: true,

          rubric: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "CriteriaGroup",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CriteriaGroup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: CriteriaGroupWhereUniqueInput
  ): Promise<CriteriaGroup | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,

          rubric: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "MarksBand",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/marksBands")
  @ApiNestedQuery(MarksBandFindManyArgs)
  async findManyMarksBands(
    @common.Req() request: Request,
    @common.Param() params: CriteriaGroupWhereUniqueInput
  ): Promise<MarksBand[]> {
    const query = plainToClass(MarksBandFindManyArgs, request.query);
    const results = await this.service.findMarksBands(params.id, {
      ...query,
      select: {
        bottom: true,
        createdAt: true,

        criteriaGroup: {
          select: {
            id: true,
          },
        },

        id: true,
        name: true,

        rubric: {
          select: {
            id: true,
          },
        },

        top: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "CriteriaGroup",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/marksBands")
  async connectMarksBands(
    @common.Param() params: CriteriaGroupWhereUniqueInput,
    @common.Body() body: MarksBandWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      marksBands: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "CriteriaGroup",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/marksBands")
  async updateMarksBands(
    @common.Param() params: CriteriaGroupWhereUniqueInput,
    @common.Body() body: MarksBandWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      marksBands: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "CriteriaGroup",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/marksBands")
  async disconnectMarksBands(
    @common.Param() params: CriteriaGroupWhereUniqueInput,
    @common.Body() body: MarksBandWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      marksBands: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
